language: java
jdk:
- oraclejdk7

# force upgrade Java8 as per https://github.com/travis-ci/travis-ci/issues/4042 (fixes compilation issue)
#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

# prevent travis running gradle assemble; let the build script do it anyway
install: true

sudo: false
# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
